# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nomadic Pita
email: your-email@example.com

description: A guide to living a free and decentralized lifestlye.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


github_repo: jekyll # the GitHub repo name for your project
github_username: sukienniko

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
twitter_link: twitter
twitter_username: sukienniko
medium_link: medium
medium_username: sukienniko
instagram_link: instagram
instagram_username: sukienniko

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.


# Build settings
markdown: kramdown
theme_color: red
remote_theme: broccolini/swiss
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
